[package]
name = "swc-transformer-static-module-record"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "*"
serde_json = "*"
swc_core = { version = "*", features = ["ast", "quote", "visit", "swc_plugin", "utils", "swc_atoms", "plugin_transform", "swc_ecma_parser", "common"] }
swc_ecma_transforms = "*"
swc_common = "*"
swc_ecma_transforms_testing = "*"
swc_ecma_parser = "*"
testing = "*"
