[package]
name = "swc-transformer-static-module-record"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1"
serde_json = "1.0"
swc_plugin = "*"
swc_common = "*"
swc_ecma_transforms = "*"
swc_ecma_transforms_testing = "*"
swc_ecma_parser = "*"
testing = "*"
