[package]
name = "swc-transformer-static-module-record"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1"
serde_json = "1"
swc_core = { version = "0.79.16", features = [
    "ecma_ast",
    "ecma_utils",
    "ecma_visit",
    "ecma_plugin_transform",
    "swc_atoms",
    "swc_plugin",
    "testing_transform",
] }
testing = "0.33.5"
tracing = { version = "0.1.37", features = ["release_max_level_off"] }
getrandom = { version = "0.2", features = ["js"] }
