[package]
name = "swc-transformer-static-module-record"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1.0.160"
serde_json = "1.0.96"
swc_core = { version = "0.75.31", features = [
    "ecma_ast",
    "ecma_utils",
    "ecma_visit",
    "ecma_plugin_transform",
    "swc_atoms",
    "swc_plugin",
    "testing_transform",
] }
testing = "0.33.5"
