[package]
name = "swc-transformer-static-module-record"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1.0.145"
serde_json = "1.0.85"
swc_core = { version = "0.27.0", features = [
    "ecma_ast",
    "ecma_utils",
    "ecma_visit",
    "plugin_transform",
    "swc_atoms",
    "swc_plugin",
    "testing_transform",
] }
testing = "0.31.0"
