export { Compartment, type CompartmentOptions } from './compartment.js'
export { createModuleLoader } from './utils/createModuleLoader.js'
export { StaticModuleRecord } from './StaticModuleRecord.js'
export type { SystemJS } from './utils/system.js'
export { simpleResolveHook } from './utils/resolver.js'
