on:
  push:
    paths:
      - 'packages/static-module-record-swc/**'
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

name: Rust
# https://github.com/actions-rs/cargo/issues/86
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: ./packages/static-module-record-swc/
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ./packages/static-module-record-swc/Cargo.toml --release --target wasm32-unknown-unknown
      - uses: actions/upload-artifact@v3
        with:
          name: wasm
          path: ./packages/static-module-record-swc/target/wasm32-unknown-unknown/release/swc_transformer_static_module_record.wasm
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: ./packages/static-module-record-swc/
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ./packages/static-module-record-swc/Cargo.toml --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path ./packages/static-module-record-swc/Cargo.toml -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./packages/static-module-record-swc/Cargo.toml
      - run: git diff --exit-code
